# Default values for spoke.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env:
  # existingSecretName:
  secretVars: {}
    # AUTH0_CLIENT_ID: foo
    # AUTH0_CLIENT_SECRET: bar
  vars:
    NODE_ENV: production
    SUPPRESS_SELF_INVITE: ''
    DST_REFERENCE_TIMEZONE: 'America/New_York'

deployment:
  port: 3000

image:
  repository: spokeapp/spoke
  tag: node-8-alpha
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - spoke.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - spoke.example.com

autoscaler:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  enabled: true
  postgresqlUsername: spoke
  postgresqlDatabase: spoke
