#!/bin/sh

CHART_DIR=./deploy/kubernetes/helm
MANIFEST_PATH=./deploy/kubernetes/kubectl/bundle.yaml

helm dependency update $CHART_DIR &&
echo "# Generated by hack/package-k8s.sh; do not edit." > $MANIFEST_PATH &&
helm template $CHART_DIR --values $CHART_DIR/ci/kubectl-values.yaml >> $MANIFEST_PATH
